[package]
name = "minitrace"
version = "0.1.0"
authors = ["The TiKV Project Authors"]
description = "A high-performance timeline tracing library for Rust, used by TiKV"
license = "Apache-2.0"
edition = "2018"

[dependencies]
pin-project = "0.4"
minitrace-macro = { path = "crates/minitrace-macro" }
lazy_static = "1.4.0"
crossbeam = "0.7"
minstant = { git = "https://github.com/zhongzc/minstant.git" }

[dependencies.futures_01]
version = "0.1"
package = "futures"

[dependencies.futures_03]
version = "0.3.1"
package = "futures"

[dev-dependencies]
# minitrace-jaeger = { path = "crates/minitrace-jaeger" }
tokio = { version = "0.2", features = ["full"] }
criterion = "0.3"
rustracing = "0.4"
opentelemetry = "0.5"
opentelemetry-jaeger = "0.4"
tracing-opentelemetry = "0.4"
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = "0.2"

[[bench]]
name = "trace"
harness = false

[[bench]]
name = "compare"
harness = false

[workspace]
members = [ "crates/*" ]

[profile.bench]
opt-level = 3
lto = true