[package]
name = "minitrace"
version = "0.1.0"
authors = ["The TiKV Project Authors"]
description = "A high-performance timeline tracing library for Rust, used by TiKV"
license = "Apache-2.0"
edition = "2018"

[dependencies]
slab = "0.4"
minstant = { git = "https://github.com/zhongzc/minstant.git" }
crossbeam = "0.7"
pin-project = "0.4"
smallvec = "1.4"

[dev-dependencies]
criterion = "0.3"
minitrace-jaeger = { path = "crates/minitrace-jaeger" }
minitrace-datadog = { path = "crates/minitrace-datadog" }
minitrace-macro = { path = "crates/minitrace-macro" }
tokio = { version = "0.2", features = ["full"] }
rustracing = "0.4"
opentelemetry = "0.5"
opentelemetry-jaeger = "0.4"
tracing-opentelemetry = "0.4"
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = "0.2"
rand = "0.7"
crossbeam = "0.7"
futures = "0.3"
hex = "*"

[[bench]]
name = "trace"
harness = false

[[bench]]
name = "compare"
harness = false

[workspace]
members = [ "crates/*" ]

[profile.bench]
opt-level = 3
lto = true
