[package]
name = "minitrace-macro"
version = "0.4.0"
authors = ["The TiKV Project Authors"]
license = "Apache-2.0"
edition = "2018"
description = "Attribute procedural macro for minitrace-rust"
homepage = "https://github.com/tikv/minitrace-rust"
repository = "https://github.com/tikv/minitrace-rust"
documentation = "https://docs.rs/minitrace-macro"
readme = "README.md"
keywords = ["tracing", "span", "datadog", "jaeger", "opentracing"]

[lib]
proc-macro = true

[dependencies]
# The macro `quote_spanned!` is added to syn in 1.0.84
syn = { version = "1.0.84", features = ["full", "parsing", "extra-traits", "proc-macro", "visit-mut"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"

[dev-dependencies]
futures = "0.3.21"
futures-timer = "3.0.2"
minitrace = { path = "../minitrace" }
test-utilities = { path = "../test-utilities" }
tokio = { version = "1", features = ["full"] }
trybuild = "1"
