[package]
name = "minitrace-datadog"
version = "0.4.1"
authors = ["The TiKV Project Authors"]
license = "Apache-2.0"
edition = "2018"
description = "Datadog reporter for minitrace-rust"
homepage = "https://github.com/tikv/minitrace-rust"
repository = "https://github.com/tikv/minitrace-rust"
documentation = "https://docs.rs/minitrace-datadog"
readme = "README.md"
keywords = ["tracing", "span", "datadog", "jaeger", "opentracing"]

[dependencies]
minitrace = { path = "../minitrace" }
rmp-serde = "1"
serde = { version = "1", features = ["derive"] }
reqwest = { version = "0.11", features = ["blocking"] }

[dev-dependencies]
futures = "0.3"
