[package]
name = "test-no-report"
version = "0.0.1"
authors = ["The TiKV Project Authors"]
license = "Apache-2.0"
edition = "2021"
readme = "README.md"
publish = false

[dependencies]
minitrace = { path = "../" }
