[package]
name = "minitrace-datadog"
version = "0.1.0"
authors = ["The TiKV Project Authors"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
minitrace = { path = "../.." }
rmp-serde = "0.14.4"
serde = "1.0.116"
reqwest = { version = "0.10", features = ["blocking"] }
