name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        rust: [stable, nightly]
    env:
      RUST_BACKTRACE: 1
    steps:
    - uses: actions/checkout@v2
    - name: Set up toolchains
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy
    - name: Check format
      run: cargo fmt --all -- --check
    - name: Lints
      run: cargo clippy --all-targets --all-features -- --deny warnings
    - name: Build
      run: cargo build --workspace --all-targets
    - name: Run tests
      run: cargo test --workspace --all-targets -- --nocapture
    - name: Run benches
      run: cargo bench --workspace --all-targets
    - name: Run examples
      run: |
        export docker="sudo docker"
        $docker run --rm -d -p6831:6831/udp -p16686:16686 --name jaeger jaegertracing/all-in-one:latest
        cargo run --example asynchronous
        cargo run --example synchronous
        cargo run --example get_started
        $docker kill $($docker ps -q)